# workflow/Snakefile

RAW_SPOTIFY = "data/raw/spotify_raw_top50_bycountry.csv"
RAW_SPOTIFY_CHECKED = "data/raw/spotify_raw_checked.csv"
RAW_WB = "data/raw/worldbank_raw.csv"

PROC_SPOTIFY = "data/processed/spotify_clean.csv"
PROC_WB = "data/processed/worldbank_clean.csv"
MERGED = "data/processed/music_culture_merged.csv"

REPORT_SUMMARY = "reports/summary_stats.md"
FIG1 = "figures/gdp_vs_popularity.png"
FIG2 = "figures/internet_vs_popularity.png"

rule all:
    input:
        RAW_SPOTIFY_CHECKED,
        RAW_WB,
        PROC_SPOTIFY,
        PROC_WB,
        MERGED,
        REPORT_SUMMARY,
        FIG1,
        FIG2

rule acquire_worldbank:
    output: RAW_WB
    shell:
        "python scripts/acquire_worldbank.py"

rule acquire_spotify:
    input: RAW_SPOTIFY
    output: RAW_SPOTIFY_CHECKED
    shell:
        "python scripts/acquire_spotify.py"

rule clean_spotify:
    input: RAW_SPOTIFY_CHECKED
    output: PROC_SPOTIFY
    shell:
        "python scripts/clean_spotify.py"

rule clean_worldbank:
    input: RAW_WB
    output: PROC_WB
    shell:
        "python scripts/clean_worldbank.py"

rule integrate:
    input:
        PROC_SPOTIFY,
        PROC_WB
    output:
        MERGED
    shell:
        "python scripts/integrate.py"

rule profile_quality:
    input: MERGED
    output: REPORT_SUMMARY
    shell:
        "python scripts/profile_quality.py"

rule analyze:
    input: MERGED
    output:
        FIG1,
        FIG2
    shell:
        "python scripts/analyze.py"

